### ISSUE TITLE
Questions about evaluate.py

### ISSUE THREAD

**Issue by SR20mlab** [secury/APAC#1]
(Please note that the question is in poor English due to the translator)

We are interested in your research and implementation of this code.

As the title says, it is difficult to reproduce the implementation because evaluate.py is not publicly available on github. Could you please make it public so that we can reproduce this one?
I apologize if this is a misunderstanding.
ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー
APAC/main.py line11 >"from evaluate import make_vectorized_env"
APAC/algorithms/APAC.py line10 > "from evaluate import evaluate_policy"
APAC/algorithms/LSAC.py line10 >"from evaluate import evaluate_policy_lsac" ...

**Comment by secury** [comment]
Hi, thanks for your interest in this repository, and sorry for the missing file.
I just added `evaluate.py` to the repository.
